name: Build GMP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-linux-x86-64:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
     
    - name: build
      run: >
        ./configure --enable-cxx --prefix=${{github.workspace}}/dist;
        make;
        make check;
        make install;

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gmp-linux-x86-64
        path: dist/*

  build-android-arm-64:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26d
        add-to-path: false

    - name: build
      run: >
        export PATH=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH;
        CC=aarch64-linux-android29-clang CXX=aarch64-linux-android29-clang++ ./configure --enable-cxx --prefix=${{github.workspace}}/dist --host=aarch64-linux-android29;
        make;
        make check || true;
        make install;

      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gmp-android-arm-64
        path: dist/*


  build-windows-x86-64:
    runs-on: windows-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4

    - uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-toolchain base-devel
  
    - name: build
      shell: msys2 {0}
      run: >
        ./configure --enable-cxx --prefix=$(cygpath -u '${{github.workspace}}')/dist;
        make;
        make check || true;
        make install;

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gmp-windows-x86-64
        path: dist/*
        
  build-macos-arm-64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: >
        brew install texinfo

    - name: Build
      run: >
        ./configure --enable-cxx --prefix=${{github.workspace}}/dist;
        make;
        make check;
        make install;

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gmp-macos-arm-64
        path: dist/*

  build-macos-x86-64:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: >
        brew install texinfo

    - name: Build
      run: >
        ./configure --enable-cxx --prefix=${{github.workspace}}/dist;
        make;
        make check || true;
        make install;

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gmp-macos-x86-64
        path: dist/*

  build-macosx-x86-64:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: >
        brew install texinfo

    - name: Build
      run: >
        ./configure --enable-cxx --prefix=${{github.workspace}}/dist CFLAGS="-mmacos-version-min=10.9" CXXFLAGS="-mmacos-version-min=10.9";
        make;
        make check || true;
        make install;

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gmp-macosx-x86-64
        path: dist/*
