name: Build GMP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos-arm-64:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: >
        ./configure --enable-cxx --prefix=${{github.workspace}}/bin;
        make install;

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gmp-macos-arm-64
        path: bin/*

  build-macos-x86-64:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: >
        brew install texinfo

    - name: Build
      run: >
        CC=clang CXX=clang++ ./configure --enable-cxx --prefix=${{github.workspace}}/bin;
        make install;

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gmp-macos-x86-64
        path: bin/*

  build-macosx-x86-64:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: >
        brew install texinfo

    - name: Build
      run: >
        CC=clang CXX=clang++ ./configure --enable-cxx --prefix=${{github.workspace}}/bin CFLAGS="-mmacos-version-min=10.9" CXXFLAGS="-mmacos-version-min=10.9";
        make install;

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: gmp-macosx-x86-64
        path: bin/*
